version: '3.8'

services:
  registry:
    image: myrmi-reg:latest
    environment:
      - RMI_ROLE=registry
      - RMI_REGISTRY_ADDRESS=registry  # Uses the service name as DNS
      - RMI_SERVER_ADDRESS=server
    ports:
      - "11099:11099"
    networks:
      - rmi-network

  server:
    image: myrmi-ser:latest
    environment:
      - RMI_ROLE=server
      - RMI_REGISTRY_ADDRESS=registry
      - RMI_SERVER_ADDRESS=server
    depends_on:
      - registry
    ports:
      - "8000:9000"
    networks:
      - rmi-network

  client:
    image: myrmi-cli:latest
    environment:
      - RMI_ROLE=client
      - RMI_REGISTRY_ADDRESS=registry
      - RMI_SERVER_ADDRESS=server
    depends_on:
      - server
    networks:
      - rmi-network

networks:
  rmi-network:
    driver: bridge
